library(reshape2)
data("airquality")
print("First few rows of the dataset:")
print(head(airquality))
manual_mean <- function(x) {
  sum_x <- sum(x, na.rm = TRUE) 
  count_x <- sum(!is.na(x)) 
  return(sum_x / count_x)
}
mean_temp <- manual_mean(airquality$Temp)
print(paste("Mean Temperature:", mean_temp))
print("First five rows of airquality dataset:")
first_five_rows <- airquality[1:5, ]
print(first_five_rows)
airquality_subset <- airquality[, !(names(airquality) %in% c("Temp", "Wind"))]
print("Data excluding Temp and Wind columns:")
print(head(airquality_subset))
coldest_temp <- min(airquality$Temp, na.rm = TRUE)
coldest_day <- airquality[airquality$Temp == coldest_temp, ]
print("Coldest day details:")
print(coldest_day)
print("Summary statistics of airquality dataset:")
print(summary(airquality))
melted_airquality <- melt(airquality)
print("Melted airquality dataset:")
print(head(melted_airquality))
melted_airquality_id <- melt(airquality, id.vars = c("Month", "Day"))
print("Melted airquality dataset with Month and Day as ID variables:")
print(head(melted_airquality_id))
casted_airquality <- dcast(melted_airquality_id, Month + Day ~ variable, mean, na.rm = TRUE)
print("Casted airquality dataset (Month and Day as features):")
print(head(casted_airquality))
monthly_avg <- dcast(melted_airquality_id, Month ~ variable, mean, na.rm = TRUE)
print("Monthly average of Ozone, Solar.R, Wind, and Temp:")
print(monthly_avg)
